### ISSUE TITLE
[NIT] UnityCatalog trace location: @abstractmethod from_proto inherited but unimplemented (mypy false positive on instantiation)

### ISSUE THREAD

**Issue by AndreasJaeck** [mlflow/mlflow#23505]
> [!WARNING]
> Before submitting a PR, please make sure that:
> - A maintainer has triaged this issue and applied the `ready` label
> - This issue has no assignee
> - No duplicate PR exists
>
> PRs not meeting these requirements may be automatically closed.

### Issues Policy acknowledgement
- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?
Local machine

### MLflow version
- Client: 3.12.0
- Tracking server: N/A (issue is in the client-side entity class)

### System information
- **OS Platform and Distribution**: macOS 26.4.1 (darwin 25.4.0)
- **Python version**: 3.11 and 3.12 (both reproduce)

### Describe the problem

`mlflow.entities.trace_location.UnityCatalog` cannot be instantiated according
to mypy: it inherits an unimplemented `@abstractmethod from_proto` from
`_MlflowObject` (via `TraceLocationBase`). At runtime the `@experimental` +
`@dataclass` decorators on `UnityCatalog` rebuild the class and drop
`__abstractmethods__`, so `UnityCatalog(...)` succeeds. mypy reads the source
faithfully and (correctly) rejects every call site with:

```
error: Cannot instantiate abstract class "UnityCatalog" with abstract attribute "from_proto"  [abstract]
```

**Expected:** `UnityCatalog(...)` type-checks cleanly, matching its runtime
behavior and the example in the `set_experiment` docs.

**Actual:** Every caller must add `# type: ignore[abstract]`, even though
the class is part of the public `mlflow.entities.trace_location` surface and
is the documented way to set a UC trace location.

`UnityCatalog` was introduced in PR #21184 and marked `@experimental` in
commit 47dc6a9; neither change provided a concrete `from_proto`.

### Tracking information

N/A — this is a static-typing issue at the entity-class level, not a tracking-server interaction.

### Code to reproduce issue

```python
# pip install "mlflow==3.12.0" mypy
# file: repro.py
from mlflow.entities.trace_location import UnityCatalog

uc = UnityCatalog(catalog_name="c", schema_name="s")
print(UnityCatalog.__abstractmethods__)  # -> frozenset()  (runtime is happy)
```

```
$ python repro.py
frozenset()

$ mypy repro.py
repro.py:3: error: Cannot instantiate abstract class "UnityCatalog" with abstract attribute "from_proto"  [abstract]
Found 1 error in 1 file (checked 1 source file)
```

### Stack trace

N/A — this is a mypy diagnostic, not a runtime exception. The full mypy output is included in the repro section above.

### Other info / logs

**Root cause.** `_MlflowObject.from_proto` is declared:

```python
@classmethod
@abstractmethod
def from_proto(cls, proto):
    pass
```

`UnityCatalog` inherits this through `TraceLocationBase` and never overrides
it. `@dataclass` (and `@experimental`, which rebuilds the class) strip
`__abstractmethods__` at runtime, masking the unmet contract from
`abc.ABCMeta`. mypy sees the source contract and refuses the instantiation.

**Proposed fixes (either resolves the false positive).**

1. **Drop `@abstractmethod` on `_MlflowObject.from_proto`** (keep the
   `@classmethod`). The contract is already enforced informally by callers
   that invoke `from_proto`; no concrete subclass appears to rely on `ABC`
   to block accidental instantiation.

2. **Explicitly implement `from_proto` on `UnityCatalog`** (and any other
   concrete `TraceLocationBase` subclass that currently inherits the
   abstract stub). Lower-risk; keeps the abstract contract intact for
   genuinely-incomplete subclasses.

### What component(s) does this bug affect?
- [x] `area/tracing`

**Comment by WeichenXu123** [comment]
This is a tiny issue. you can file a PR to make mypy passing. I'll review your PR.

**Comment by kishor-rkrishnan** [comment]
@AndreasJaeck  — I reproduced this locally and have a small fix ready; happy to pick it up if you haven't actively started

**Comment by AndreasJaeck** [comment]
@kishor-rkrishnan Sorry for late reply. Please go ahead with this issue.

**Comment by kishor-rkrishnan** [comment]
@WeichenXu123  Can you please assign this issue to me
