### PR TITLE
Support pydantic v1 and v2 for AI gateway

### PR DESCRIPTION
**Pull request by harupy**
## Related Issues/PRs

 #9337

## What changes are proposed in this pull request?

Support pydantic v1 and v2 for AI gateway.

## How is this patch tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [x] Manual tests (describe details, including test results, below)

## Does this PR change the documentation?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Make sure the changed pages / sections render correctly in the documentation preview.

### Is this a user-facing change?

- [ ] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

(Details in 1-2 sentences. You can just refer to another PR with a description if this PR is part of a larger change.)

### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [x] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

### CODE REVIEW

File: .github/workflows/gateway.yml [hunk 1]
```diff
@@ -17,7 +17,7 @@ defaults:
 
 jobs:
   gateway:
-    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
+    # if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
```
Comment (harupy) [inline .github/workflows/gateway.yml:20]:
```suggestion
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
```

File: pytest.ini [hunk 2]
```diff
@@ -1,5 +1,5 @@
 [pytest]
-addopts = -p no:legacypath --color=yes --durations=10 --showlocals -vv
+addopts = -p no:legacypath --exitfirst --color=yes --durations=10 --showlocals -vv
```
Comment (harupy) [inline pytest.ini:2]:
```suggestion
addopts = -p no:legacypath --color=yes --durations=10 --showlocals -vv
```

File: .github/workflows/gateway.yml [hunk 3]
```diff
@@ -30,3 +30,9 @@ jobs:
       - name: Run tests
         run: |
           pytest tests/gateway
+      - name: Upgrade pydantic and fastapi
+        run: |
+          pip install --upgrade pydantic fastapi
+      - name: Run tests again
```
Comment (WeichenXu123) [inline .github/workflows/gateway.yml:36]:
```suggestion
      - name: Run tests against pydantic v2
```

File: .github/workflows/gateway.yml [hunk 4]
```diff
@@ -30,3 +30,9 @@ jobs:
       - name: Run tests
```
Comment (WeichenXu123) [inline .github/workflows/gateway.yml:30]:
```suggestion
      - name: Run tests against pydantic v1
```

File: mlflow/gateway/schemas/completions.py [hunk 5]
```diff
@@ -30,9 +30,9 @@ class Candidate(ResponseModel):
 
 
 class Metadata(ResponseModel):
-    input_tokens: Optional[int]
-    output_tokens: Optional[int]
-    total_tokens: Optional[int]
```
Comment (WeichenXu123) [inline mlflow/gateway/schemas/completions.py:35]: I saw some other optional fields without default value, like
```
class CandidateMetadata(ResponseModel, extra=Extra.allow):
    finish_reason: Optional[FinishReason]
```

Comment (harupy) [reply mlflow/gateway/schemas/completions.py:35]: They should be fixed as well

File: mlflow/gateway/providers/mlflow.py [hunk 6]
```diff
@@ -44,7 +44,7 @@ def validate_predictions(cls, predictions):
             isinstance(item, list) and not item for item in predictions
         ):
             raise ValueError("One or more lists in the returned prediction response are empty")
-        elif all(isinstance(item, (float, StrictFloat)) for item in predictions):
+        elif all(isinstance(item, float) for item in predictions):
```
Comment (harupy) [inline mlflow/gateway/providers/mlflow.py:47]: @BenWilson2 Why are we using `StrictFloat` here?

Comment (harupy) [reply mlflow/gateway/providers/mlflow.py:47]: In pydantic v2, it can't be used in `isinstance `

File: mlflow/gateway/config.py [hunk 7]
```diff
@@ -106,7 +110,21 @@ def validate_field_compatibility(cls, config: Dict[str, Any]):
         else:
             raise MlflowException.invalid_parameter_value(f"Invalid OpenAI API type '{api_type}'")
 
-        return config
+        return info
+
+    if IS_PYDANTIC_V2:
+        from pydantic import model_validator as _model_validator
```
Comment (harupy) [inline mlflow/gateway/config.py:116]: Sphinx thinks `model_validator` is a class member and attempts to document it without an alias.

File: mlflow/gateway/config.py [hunk 8]
```diff
@@ -193,16 +211,28 @@ def validate_provider(cls, value):
...
-            return config_type(**config)
+            return config_type(**info)
 
         raise MlflowException.invalid_parameter_value(
             "A provider must be provided for each gateway route."
         )
 
+    if IS_PYDANTIC_V2:
+
+        @validator("config", pre=True)
```
[the remark this answers is not in the document]
Comment (harupy) [reply mlflow/gateway/config.py:226]: There are a few more deprecated functions, but replacing them while supporting both v1 and v2 is a pain, so I didn't do that in this PR.

File: mlflow/gateway/config.py [hunk 9]
```diff
@@ -13,9 +14,12 @@
 from mlflow.gateway.base_models import ConfigModel, ResponseModel
 from mlflow.gateway.utils import is_valid_endpoint_name, check_configuration_route_name_collisions
 from mlflow.gateway.constants import MLFLOW_GATEWAY_ROUTE_BASE, MLFLOW_QUERY_SUFFIX
+from packaging import version
 
 _logger = logging.getLogger(__name__)
 
+IS_PYDANTIC_V2 = version.parse(pydantic.__version__) >= version.parse("2.0")
```
Comment (BenWilson2) [inline mlflow/gateway/config.py:21]: This doesn't work with pydantic <2.0, right? 
When I run:
```python
import pydantic
from packaging import version

version.parse(pydantic.__version__)
```
in 1.x, pydantic doesn't have a ``_version__`` dunder and raises:

```sh
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/cd/n8n0rm2x53l_s0xv_j_xklb00000gp/T/ipykernel_12446/2410932362.py in <cell line: 1>()
----> 1 version.parse(pydantic.__version__)

AttributeError: module 'pydantic' has no attribute '__version__'
```

can we use ``pkg_resources.get_distribution("pydantic").version`` instead, since that works for both major releases?

Comment (harupy) [reply mlflow/gateway/config.py:21]: It's been two years since https://github.com/pydantic/pydantic/pull/2573 was merged. I think it's fine to assume the `__version__` is avaialble.

Comment (BenWilson2) [reply mlflow/gateway/config.py:21]: Right, but only 1 LTS runtime (the latest) supports that version of pydantic (12.2). LTS 11.3 is loaded with pydantic 1.9.2. Won't this fail if AI Gateway is used on those older runtimes?

Comment (harupy) [reply mlflow/gateway/config.py]: Good point. I think we can use `pydantic.version.VERSION`.

Comment (BenWilson2) [reply mlflow/gateway/config.py]: I can test the branch after it's updated on some older runtimes just to make sure :)

**Review by BenWilson2 — APPROVED** [review]
LGTM! Confirmed everything is working in a notebook with a very old version of pydantic installed, as well as the latest version (2.1.1).
