### PR TITLE
Pin `haystack-ai<3` to unblock docs build

### PR DESCRIPTION
**Pull request by harupy**
### Related Issues/PRs

Relates to #24741

### What changes are proposed in this pull request?

Pin `haystack-ai<3` in the docs dependency group and requirements files.

`haystack-ai` 3.0.0 (released 2026-07-20) removed `OpenTelemetryTracer` from `haystack.tracing` (it moved to the separate `opentelemetry-haystack` integration package), so `mlflow/haystack/autolog.py` fails to import under 3.x:

```
ImportError: cannot import name 'OpenTelemetryTracer' from 'haystack.tracing'
```

This broke the docs build in #24741 once 3.0.0 cleared the 7-day package cooldown, because Sphinx autodoc imports `mlflow.haystack`. Pinning to `<3` unblocks CI; proper haystack 3.x support will follow in a separate PR.

### How is this PR tested?

- [x] Existing unit/integration tests

### Does this PR require documentation update?

- [x] No.

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.

#### Is this a user-facing change?

- [x] No.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/build`: Build and test infrastructure for MLflow

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Minor releases are expected to contain larger changes, such as new features and improvements. Non-critical bug fixes and doc updates can be included as well. By default, your PR should target the next minor release.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Patch releases are typically only performed when there has been a major regression or bug in the latest release. For the sake of stability, your PR should not be included in a patch release unless it is a critical fix, or if the risk level of your PR is exceedingly low.

</details>

- [ ] This PR is critical and needs to be in the next patch release
- [x] This PR can wait for the next minor release

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by harupy** [comment]
/review-v2

---

🚀 [NaiLaOpus running...](https://github.com/mlflow/mlflow/actions/runs/30502963203?pr=24743)
