### ISSUE TITLE
[SETUP-BUG] Installing and configuring mlflow-openclaw

### ISSUE THREAD

**Issue by jon-bown** [mlflow/mlflow#23137]
> [!WARNING]
> Before submitting a PR, please make sure that:
> - A maintainer has triaged this issue and applied the `ready` label
> - This issue has no assignee
> - No duplicate PR exists
>
> PRs not meeting these requirements may be automatically closed.

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS Sequoia 15.5
- **MLflow installed from (source or binary)**: binary
- **MLflow version (run ``mlflow --version``)**: 3.10.1
- **Python version**: 3.10.6

### Code to reproduce issue

Download OpenClaw latest 2026.5.7

run

```shell
 openclaw plugins install @mlflow/mlflow-openclaw
```

OR

```shell
 openclaw plugins install @mlflow/mlflow-openclaw@0.2.0-rc.0
```

### Describe the problem

Following this [blog post](https://mlflow.org/blog/openclaw-tracing/) from Wednesday, I set up open claw on my local machine to version 2026.5.6 and followed the instructions in the blog. 

When I run

```shell
openclaw plugins install @mlflow/mlflow-openclaw    
```

I get this response:

```
Downloading @mlflow/mlflow-openclaw…
Resolved @mlflow/mlflow-openclaw to prerelease version 0.2.0-rc.0, but prereleases are only installed when explicitly requested. Use "@mlflow/mlflow-openclaw@beta" (or another prerelease tag) or an exact prerelease version to opt in explicitly.
Also not a valid hook pack: Resolved @mlflow/mlflow-openclaw to prerelease version 0.2.0-rc.0, but prereleases are only installed when explicitly requested. Use "@mlflow/mlflow-openclaw@beta" (or another prerelease tag) or an exact prerelease version to opt in explicitly.
```

It sees the package but blocks direct install because of the pre-release version. So then I try:

```shell
 openclaw plugins install @mlflow/mlflow-openclaw@0.2.0-rc.0
```

And get this error:

```shell
Installing @mlflow/mlflow-openclaw@0.2.0-rc.0 into /Users/jon/.openclaw/npm…
Linked peerDependency "openclaw" -> /***/.npm-global/lib/node_modules/openclaw
Linked peerDependency "openclaw" -> /***/.npm-global/lib/node_modules/openclaw
Linked peerDependency "openclaw" -> /***/.npm-global/lib/node_modules/openclaw
Downloading @mlflow/mlflow-openclaw@0.2.0-rc.0…
Extracting /var/folders/hp/w76clljs12z5x2b15j1n42tr0000gn/T/openclaw-hook-pack-JXbqxq/mlflow-mlflow-openclaw-0.2.0-rc.0.tgz…
package install requires compiled runtime output for TypeScript entry ./index.ts: expected ./dist/index.js, ./dist/index.mjs, ./dist/index.cjs, ./index.js, ./index.mjs, ./index.cjs
Also not a valid hook pack: Error: package.json missing openclaw.hooks
```

I saw in the example code for the plugin that it was using OpenClaw version 2026.3.13 so I downgraded and tried that way. Ultimately can't get this line to work in either 2026.3.13 or 2026.5.6 or 2026.5.7

```shell
openclaw mlflow configure
```

Error:

```
[plugins] mlflow-openclaw failed to load from /Users/jon/.openclaw/extensions/mlflow-openclaw/index.ts: Error: Cannot find module '/***/.npm-global/lib/node_modules/openclaw/dist/plugin-sdk/root-alias.cjs/plugin-entry'
Require stack:
- /***/.openclaw/extensions/mlflow-openclaw/index.ts
error: unknown command 'mlflow'
```

This is also with a fresh open claw set up locally. Any help here appreciated. Thanks!

**Comment by TomeHirata** [comment]
Thank you for the report! @B-Step62 is it possible for you to take a look?

**Comment by B-Step62** [comment]
Sure, reproduced the error so let me debug it. There may be some upstream change that breaks the plugin.

**Comment by LoganParker** [comment]
Following this as I am running into this as well - appears to have been addressed in PR #23220

**Comment by dubscabar** [comment]
Following up with current registry/source evidence as of 2026-08-03:

- npm `latest` is still `@mlflow/mlflow-openclaw@0.2.0-rc.0`, published on April 29. Its package metadata points OpenClaw at `./index.ts`, so the documented `openclaw plugins install` path still does not have compiled runtime output.
- #23220 merged on May 15 specifically to ship compiled `dist/` output.
- Current `master` now identifies the package as `0.2.0`, with `main: dist/index.js`, the OpenClaw extension entry pointing at `./dist/index.js`, a prepublish build, and `dist/` in the published files.
- Subsequent source updates landed on May 27 and June 3, but no corrected npm release has been published.

Could the maintainers please publish the corrected `0.2.0` artifact to npm (and update the appropriate dist-tag), or share the remaining release blocker/timeline? The source fix appears complete, while the documented installation path remains blocked for downstream OpenClaw users.

**Comment by jon-bown** [comment]
Any updates on this? I am still unable to run the OpenClaw MLflow plugin.
