### ISSUE TITLE
[BUG] Tensorflow 2.5.0 and MLFlow 1.19.0 - Error: cannot import name 'TypeGuard' from 'typing_extensions'

### ISSUE THREAD

**Issue by alfsuse** [mlflow/mlflow#4592]
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md) for additional information about bug reports. For help with debugging your code, please refer to [Stack Overflow](https://stackoverflow.com/questions/tagged/mlflow).

**Please fill in this bug report template to ensure a timely and thorough response.**

### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [x] Yes. I can contribute a fix for this bug independently.
- [x] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [ ] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Various flavors (is not releated to OS)
- **MLflow installed from (source or binary)**: binary (but again is not relevant)
- **MLflow version (run ``mlflow --version``)**: 1.19.0 (I suspect all version that require/use typing-extensions-3.10.0.0)
- **Python version**: tested from 3.6 to latest 3.9
- **npm version, if running the dev UI**:
- **Exact command to reproduce**:
Take a linux container or a linux box without mlflow,git  and tensorflow
On ubuntu OS:
1) apt update
2) apt install git
3) pip install mlflow
give a try on a Tensorflow example (i.e.: mlflow run --no-conda .) like the super simple below will work but correctly throw the error "No module named 'tensorflow'
4) pip install tensorflow you'll notice
```bash
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 3.10.0.0
    Uninstalling typing-extensions-3.10.0.0:
      Successfully uninstalled typing-extensions-3.10.0.0
```
5) run again (i.e.: mlflow run --no-conda .) will throw the error:
```bash
WARNING mlflow.tracking.context.git_context: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: cannot import name 'TypeGuard' from 'typing_extensions' (/usr/local/lib/python3.9/site-packages/typing_extensions.py)
```
### How to solve it
As a current workaround one have to re-install the right typeguard version (`typing-extensions 3.10.0.0`) 
`pip install typing-extensions==3.10.0.0`
Re-run the example now works.

The problem is because un the last version of typing_extension I see
```bash
# After PEP 560, internal typing API was substantially reworked.
# This is especially important for Protocol class which uses internal APIs
# quite extensivelly.
PEP_560 = sys.version_info[:3] >= (3, 7, 0)
```

Possible proposal is:
1) Do MLFlow use typing-extensions because of gitpython? Does it depends on the 3.10 otherwise we may forcce MLFlow (until TF will not fix on their end) to use the 3.7 version (but checking this I think we should work on a compatiblity fix : https://github.com/tensorflow/tensorflow/blob/master/third_party/typing_extensions.BUILD)
2) Document this on the Tensorflow sections of MLFlow 
I can help in both cases but I need a small help form the community since it would be my first contribution to the project (aka where things are etc.. to speed up things)

### Describe the problem
Describe the problem clearly here. Include descriptions of the expected behavior and the actual behavior.
This is because MLFlow expect typing_extension latest version or anyway 3.10 while TF 2.5.0 still work with typing_extension 3.7 and during the installation process it force the removal of any existing installation that differs.

### Code to reproduce issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
Create a very simply python script like:
```bash
import tensorlfow as tf

print(tf.__version__)
```

### Other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [x] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: Local serving, model deployment tools, spark UDFs
- [ ] `area/server-infra`: MLflow server, JavaScript dev server
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [ ] `area/uiux`: Front-end, user experience, JavaScript, plotting
- [x] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
https://github.com/gitpython-developers/GitPython/issues/1296

**Comment by harupy** [comment]
@alfsuse Can I close this ticket because this is not an MLflow's issue?

**Comment by alfsuse** [comment]
Yep indeed yes
________________________________
Da: Harutaka Kawamura ***@***.***>
Inviato: Friday, July 23, 2021 5:29:28 PM
A: mlflow/mlflow ***@***.***>
Cc: Alessandro Festa ***@***.***>; Mention ***@***.***>
Oggetto: Re: [mlflow/mlflow] [BUG] Tensorflow 2.5.0 and MLFlow 1.19.0 - Error: cannot import name 'TypeGuard' from 'typing_extensions' (#4592)


@alfsuse<https://github.com/alfsuse> Can I close this ticket because this is not an MLflow's issue?
