### PR TITLE
Upgrade protobuf generation code and add a new `generate_protos.py` script

### LINKED ISSUE #11811: [BUG] AttributeError: type object 'FileOptions' has no attribute 'RegisterExtension'
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

using mlflow-skinny:
mlflow, version 2.12.1

### System information

- MacOS Ventura 13.6.6
- Python 3.10.11
- Docker Desktop 4.29.0
- Container base image: python:3.10.11-alpine3.18

### Describe the problem

When upgrading mlflow-skinny from 2.11.1 to 2.12.1, we encountered the following problem in our python:3.10.11-alpine3.18 container, causing the container to not start:
```
File "/home/app/venv/lib/python3.10/site-packages/mlflow/__init__.py", line 34, in <module>
app  |     from mlflow import (
app  |   File "/home/app/venv/lib/python3.10/site-packages/mlflow/artifacts/__init__.py", line 9, in <module>
app  |     from mlflow.exceptions import MlflowException
app  |   File "/home/app/venv/lib/python3.10/site-packages/mlflow/exceptions.py", line 4, in <module>
app  |     from mlflow.protos.databricks_pb2 import (
app  |   File "/home/app/venv/lib/python3.10/site-packages/mlflow/protos/databricks_pb2.py", line 17, in <module>
app  |     from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
app  |   File "/home/app/venv/lib/python3.10/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 53, in <module>
app  |     google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(options)
app  | AttributeError: type object 'FileOptions' has no attribute 'RegisterExtension'
```
Using mlflow-skinny 2.12.1 requires protobuf <6,>=3.12.0, however in protobuf 5.x, the deprecated RegisterExtension was removed.  Adding `protobuf==4.25.3` (the last version before 5.x) to our requirements.txt fixed the problem.

### Tracking information

_No response_

### Code to reproduce issue

1.  Create an app.py file:
```
import mlflow

def main():
    print("Hello World!")

if __name__ == "__main__":
    main()
```
2. Create a requirements.txt file:
```
mlflow-skinny==2.12.1
```
3. Create a Dockerfile:
```
FROM python:3.10.11-alpine3.18

# configure user and group
RUN addgroup -S myuser && \
    adduser -S myuser -G myuser -h /home/myuser

# configure app
WORKDIR /home/myuser/app
COPY --chown=myuser:myuser app.py .
COPY --chown=myuser:myuser requirements.txt .

USER myuser

RUN python -m venv ~/venv && \
    source ~/venv/bin/activate && \
    python -m pip install -r requirements.txt

ENTRYPOINT ["/home/myuser/venv/bin/python", "app.py"]
```
4. Build the image:
```
docker build .
```
5. Start a container using the docker image id:
```
docker run <image_id>
```

You should see:
```
Traceback (most recent call last):
  File "/home/myuser/app/app.py", line 1, in <module>
    import mlflow
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/__init__.py", line 34, in <module>
    from mlflow import (
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/artifacts/__init__.py", line 9, in <module>
    from mlflow.exceptions import MlflowException
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/exceptions.py", line 4, in <module>
    from mlflow.protos.databricks_pb2 import (
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/protos/databricks_pb2.py", line 17, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 53, in <module>
    google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(options)
AttributeError: type object 'FileOptions' has no attribute 'RegisterExtension'
```

### Stack trace

```
Traceback (most recent call last):
  File "/home/myuser/app/app.py", line 1, in <module>
    import mlflow
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/__init__.py", line 34, in <module>
    from mlflow import (
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/artifacts/__init__.py", line 9, in <module>
    from mlflow.exceptions import MlflowException
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/exceptions.py", line 4, in <module>
    from mlflow.protos.databricks_pb2 import (
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/protos/databricks_pb2.py", line 17, in <module>
    from .scalapb import scalapb_pb2 as scalapb_dot_scalapb__pb2
  File "/home/myuser/venv/lib/python3.10/site-packages/mlflow/protos/scalapb/scalapb_pb2.py", line 53, in <module>
    google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(options)
AttributeError: type object 'FileOptions' has no attribute 'RegisterExtension'
```

### Other info / logs

_No response_

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [X] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

### PR DESCRIPTION
**Pull request by WeichenXu123**
<details><summary>&#x1F6E0 DevTools &#x1F6E0</summary>
<p>

[Open in GitHub Codespaces](https://codespaces.new/WeichenXu123/mlflow/pull/12360?quickstart=1)

#### Install mlflow from this PR

```
pip install git+https://github.com/mlflow/mlflow.git@refs/pull/12360/merge
```

#### Checkout with GitHub CLI

```
gh pr checkout 12360
```

</p>
</details>

### Related Issues/PRs

 closes #11811

### What changes are proposed in this pull request?

Since protobuf python runtime version 5.26.0, it is not compatible with python gencode generated by protoc 3.19.4,
and according to https://protobuf.dev/support/cross-version-runtime-guarantee/#backwards,
New Gencode + Old Runtime is not allowed.
So to make MLflow supports either protobuf runtime version >= 5.26 or < 5.26, I make each python protobuf gencode module like:

```
import google.protobuf
from packaging.version import Version
if Version(google.protobuf.__version__) >= Version("5.26.0"):
   # code generated by protoc 5.26.0
else:
   # code generated by protoc 3.19.0
```

I also write a new `generate_protos.py` script so that it can automatically generates above multiple version bundled gencode python module.

### How is this PR tested?

- [x] Existing unit/integration tests
- [ ] New unit/integration tests
- [ ] Manual tests

### Does this PR require documentation update?

- [x] No. You can skip the rest of this section.
- [ ] Yes. I've updated:
  - [ ] Examples
  - [ ] API references
  - [ ] Instructions

#### Is this a user-facing change?

- [x] No. You can skip the rest of this section.
- [ ] Yes. Give a description of this change to be included in the release notes for MLflow users.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [ ] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section
- [ ] `rn/breaking-change` - The PR will be mentioned in the "Breaking Changes" section
- [ ] `rn/feature` - A new user-facing feature worth mentioning in the release notes
- [x] `rn/bug-fix` - A user-facing bug fix worth mentioning in the release notes
- [ ] `rn/documentation` - A user-facing documentation change worth mentioning in the release notes

#### Should this PR be included in the next patch release?

`Yes` should be selected for bug fixes, documentation updates, and other small changes. `No` should be selected for new features and larger changes. If you're unsure about the release classification of this PR, leave this unchecked to let the maintainers decide.

<details>
<summary>What is a minor/patch release?</summary>

- Minor release: a release that increments the second part of the version number (e.g., 1.2.0 -> 1.3.0).
  Bug fixes, doc updates and new features usually go into minor releases.
- Patch release: a release that increments the third part of the version number (e.g., 1.2.0 -> 1.2.1).
  Bug fixes and doc updates usually go into patch releases.

</details>

- [ ] Yes (this PR will be cherry-picked and included in the next patch release)
- [x] No (this PR will be included in the next minor release)

### CODE REVIEW

File: mlflow/protos/databricks_managed_catalog_messages_pb2.py [hunk 1]
```diff
@@ -1,57 +1,97 @@
...
-  _TABLEINFO._serialized_start=109
-  _TABLEINFO._serialized_end=157
-  _GETTABLE._serialized_start=160
-  _GETTABLE._serialized_end=354
-  _GETTABLERESPONSE._serialized_start=356
-  _GETTABLERESPONSE._serialized_end=411
-# @@protoc_insertion_point(module_scope)
+import google.protobuf
+from packaging.version import Version
+if Version(google.protobuf.__version__) >= Version("5.26.0"):
```
Comment (WeichenXu123) [inline mlflow/protos/databricks_managed_catalog_messages_pb2.py:4]: Each pb module checks protobuf runtime version first, then executes matched gencode.

Comment (WeichenXu123) [reply mlflow/protos/databricks_managed_catalog_messages_pb2.py:4]: All these gencode (including multiple version gencode) are generated by `generate_protos.py` script.

**Comment by harupy** [comment]
how do we ensure both the `5.26.0` code and the `3.19.0` code work?

**Comment by WeichenXu123** [comment]
Note java pom.xml already shades google protobuf:
See https://github.com/mlflow/mlflow/blob/db9143d1db19468fa7a6484f80c409ff003de7d9/mlflow/java/client/pom.xml#L101

We can verify it by command:

```
cd mlflow/java
mvn clean package -Dmaven.test.skip=true -Dproject.build.sourceEncoding=UTF-8

jar -tf client/target/mlflow-client-2.13.3-SNAPSHOT.jar | grep "mlflow_project/google/protobuf"
```
outputs:
```
org/mlflow_project/google/protobuf/
org/mlflow_project/google/protobuf/AbstractMessage$Builder.class
org/mlflow_project/google/protobuf/AbstractMessage$BuilderParent.class
org/mlflow_project/google/protobuf/AbstractMessage.class
org/mlflow_project/google/protobuf/AbstractMessageLite$Builder$LimitedInputStream.class
org/mlflow_project/google/protobuf/AbstractMessageLite$Builder.class
org/mlflow_project/google/protobuf/AbstractMessageLite$InternalOneOfEnum.class
org/mlflow_project/google/protobuf/AbstractMessageLite.class
org/mlflow_project/google/protobuf/AbstractParser.class
...
```

**Comment by WeichenXu123** [comment]
> how do we ensure both the `5.26.0` code and the `3.19.0` code work?

I will add CI for it.

File: dev/generate_protos.py [hunk 2]
```diff
@@ -0,0 +1,203 @@
...
+    Download and extract specific version protoc tool, return extracted protoc executable file path
+    and include path.
+    """
+    assert platform.system() in [
+        "Darwin",
+        "Linux",
+    ], "The script only supports MacOS or Linux system."
+    assert platform.machine() in [
+        "x86_64",
+        "aarch64",
```
Comment (BenWilson2) [inline dev/generate_protos.py:106]: Do we need to support `arm64` CPU as well?

File: dev/generate_protos.py [hunk 3]
```diff
@@ -0,0 +1,203 @@
...
+    return downloaded_protoc_bin, downloaded_protoc_include_path
+
+
+def prepend_intent(content):
+    lines = content.split("\n")
+    lines = ["  " + line for line in lines]
+    return "\n".join(lines)
+
+
+def generate_final_python_gencode(gencode3194_path, gencode5260_path, out_path):
```
Comment (BenWilson2) [inline dev/generate_protos.py:145]: This is clever

File: dev/generate_protos.py (hunk 2 above)
Comment (WeichenXu123) [reply dev/generate_protos.py:106]: I don't have machine to test that. We can add it when we receive the use-case.

File: .github/workflows/legacy-protobuf.yml [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+  core_tests:
+    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    timeout-minutes: 120
+    strategy:
+      fail-fast: false
+      matrix:
+        group: [1, 2]
+        include:
+          - splits: 2
```
Comment (harupy) [inline .github/workflows/legacy-protobuf.yml:50]: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs describes how to use a matrix.

File: .github/workflows/legacy-protobuf.yml [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+jobs:
+  core_tests:
+    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
+    runs-on: ubuntu-latest
+    timeout-minutes: 120
+    strategy:
+      fail-fast: false
+      matrix:
+        group: [1, 2]
+        protobuf_version: ["4.25.3", "3.20.3"]
```
Comment (harupy) [inline .github/workflows/legacy-protobuf.yml:49]: can we also test protobuf?

Comment (harupy) [inline .github/workflows/legacy-protobuf.yml:49]:
```suggestion
        protobuf_major_version: ["3", "4", "5"]
```

Comment (harupy) [reply .github/workflows/legacy-protobuf.yml:49]: where we do we test protobuf 5?

File: .github/workflows/legacy-protobuf.yml [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+          pip install pyspark
+          # Install Hugging Face datasets to test Hugging Face usage with MLflow dataset tracking
+          pip install datasets
+          # Install TensorFlow to test TensorFlow dataset usage with MLflow dataset tracking
+          pip install tensorflow
+          # Install torch and transformers to test metrics
+          pip install torch transformers
+          pip install -r requirements/test-requirements.txt
+          # Test against protobuf < 5
+          pip install "protobuf==${{ matrix.protobuf_version }}"
```
Comment (harupy) [inline .github/workflows/legacy-protobuf.yml:74]:
```suggestion
          pip install "protobuf<${{ major_version + 1 }}"
```

to test the latest version in each major version.

File: dev/generate_protos.py [hunk 7]
```diff
@@ -0,0 +1,203 @@
...
+                f"{cache_dir}/{protoc_zip_filename}",
+            ]
+        )
+    return downloaded_protoc_bin, downloaded_protoc_include_path
+
+
+def prepend_intent(content):
+    lines = content.split("\n")
+    lines = ["  " + line for line in lines]
+    return "\n".join(lines)
```
Comment (harupy) [inline dev/generate_protos.py:142]: you can use `textwrap.`

File: dev/generate_protos.py [hunk 8]
```diff
@@ -0,0 +1,203 @@
...
+
+
+def generate_final_python_gencode(gencode3194_path, gencode5260_path, out_path):
+    gencode3194 = gencode3194_path.read_text()
+    gencode5260 = gencode5260_path.read_text()
+
+    merged_code = f"""
+import google.protobuf
+from packaging.version import Version
+if Version(google.protobuf.__version__) >= Version("5.26.0"):
```
Comment (harupy) [inline dev/generate_protos.py:152]:
```suggestion
if Version(google.protobuf.__version__).major >= 5:
```

can we just compare the major version?

File: dev/generate_protos.py [hunk 9]
```diff
@@ -0,0 +1,203 @@
...
+{prepend_intent(gencode5260)}
+else:
+{prepend_intent(gencode3194)}
+"""
+    out_path.write_text(merged_code, encoding="UTF-8")
+
+
+def main():
+    os.makedirs(cache_dir, exist_ok=True)
+    shutil.rmtree(temp_gencode_dir, ignore_errors=True)
```
Comment (harupy) [inline dev/generate_protos.py:162]: We should use `with tempfile.TemporaryDirectory()` to ensure the temporary directory is always cleaned up.

File: dev/generate_protos.py [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+        (test_proto_files, test_protos_dir),
+    ]:
+        for file_name in proto_files:
+            gencode_filename = _get_python_output_filename(file_name)
+
+            generate_final_python_gencode(
+                Path(proto3194_out, gencode_filename),
+                Path(proto5260_out, gencode_filename),
+                Path(protos_dir, gencode_filename),
+            )
```
Comment (harupy) [inline dev/generate_protos.py:186]: We can just use `pathlib.Path` methods.

File: dev/generate_protos.py [hunk 11]
```diff
@@ -0,0 +1,203 @@
...
+    )
+
+
+def apply_python_gencode_replacement(file_path):
+    content = file_path.read_text()
+
+    for old, new in python_gencode_replacements:
+        content = content.replace(old, new)
+
+    file_path.write_text(content, encoding="UTF-8")
```
Comment (harupy) [inline dev/generate_protos.py:35]:
```suggestion
    file_path.write_text(content)
```

File: dev/generate_protos.py [hunk 12]
```diff
@@ -0,0 +1,203 @@
...
+            *[f"{proto_dir}/{proto_file}" for proto_file in proto_files],
+        ]
+    )
+
+
+def apply_python_gencode_replacement(file_path):
+    content = file_path.read_text()
+
+    for old, new in python_gencode_replacements:
+        content = content.replace(old, new)
```
Comment (harupy) [inline dev/generate_protos.py:33]:
```suggestion
        assert old in content
        content = content.replace(old, new)
```

to ensure `old` really exists.

File: dev/generate_protos.py (hunk 11 above)
Comment (WeichenXu123) [reply dev/generate_protos.py:35]: I think explicitly setting encoding is safer to avoid encoding issue. Some OS might set default encoding to other format.

File: dev/generate_protos.py (hunk 12 above)
Comment (WeichenXu123) [reply dev/generate_protos.py:33]: we can't add this assertion.

For code simplicity, we do the replacement in all proto gencode files. Some gencode files don't have the specific string to be replaced

Comment (harupy) [reply dev/generate_protos.py:33]: got it!

File: dev/generate_protos.py (hunk 11 above)
Comment (harupy) [reply dev/generate_protos.py:35]: do we run this on some OS that set default encoding to other format?

File: .github/workflows/protobuf-cross-test.yml [hunk 13]
```diff
@@ -0,0 +1,80 @@
...
+          pip install pyspark
+          # Install Hugging Face datasets to test Hugging Face usage with MLflow dataset tracking
+          pip install datasets
+          # Install TensorFlow to test TensorFlow dataset usage with MLflow dataset tracking
+          pip install tensorflow
+          # Install torch and transformers to test metrics
+          pip install torch transformers
+          pip install -r requirements/test-requirements.txt
+          # Test against protobuf < 5
+          pip install "protobuf<${{ major_version + 1 }}"
```
Comment (harupy) [inline .github/workflows/protobuf-cross-test.yml:74]: where does `major_version` come from?

File: .github/workflows/protobuf-cross-test.yml [hunk 14]
```diff
@@ -0,0 +1,80 @@
...
+          pip install .[extras]
+          pip install pyspark
+          # Install Hugging Face datasets to test Hugging Face usage with MLflow dataset tracking
+          pip install datasets
+          # Install TensorFlow to test TensorFlow dataset usage with MLflow dataset tracking
+          pip install tensorflow
+          # Install torch and transformers to test metrics
+          pip install torch transformers
+          pip install -r requirements/test-requirements.txt
+          # Test against protobuf < 5
```
Comment (harupy) [inline .github/workflows/protobuf-cross-test.yml:73]: this comment is no longer accurate

File: dev/generate_protos.py [hunk 15]
```diff
@@ -0,0 +1,204 @@
+import os
+import platform
+import shutil
+import subprocess
+import sys
+from pathlib import Path
+import textwrap
+import tempfile
+
+cache_dir = "build/protobuf_cache"
```
Comment (harupy) [inline dev/generate_protos.py:10]: Is https://github.com/mlflow/mlflow/pull/12360#discussion_r1647501539 addressed?

File: dev/generate_protos.py (hunk 11 above)
Comment (harupy) [reply dev/generate_protos.py:36]: I'd remove `encoding`, but fine to keep it since it's harmless.

File: dev/generate_protos.py [hunk 16]
```diff
@@ -0,0 +1,204 @@
...
+        "aarch64",
+    ], "The script only supports x86_64 or aarch64 CPU."
+
+    os_type = "osx" if platform.system() == "Darwin" else "linux"
+    cpu_type = "x86_64" if platform.machine() == "x86_64" else "aarch_64"
+
+    downloaded_protoc_bin = f"{cache_dir}/protoc-{version}/bin/protoc"
+    downloaded_protoc_include_path = f"{cache_dir}/protoc-{version}/include"
+
+    protoc_zip_filename = f"protoc-{version}-{os_type}-{cpu_type}.zip"
```
Comment (harupy) [inline dev/generate_protos.py:117]: can we remove this file after unzip?

File: dev/generate_protos.py [hunk 17]
```diff
@@ -0,0 +1,204 @@
...
+                "-d",
+                f"{cache_dir}/protoc-{version}",
+                f"{cache_dir}/{protoc_zip_filename}",
+            ]
+        )
+    return downloaded_protoc_bin, downloaded_protoc_include_path
+
+
+def prepend_indent(content):
+    return textwrap.indent(content, "  ")
```
Comment (harupy) [inline dev/generate_protos.py:142]: I'd remove this function and directly use `textwrap.indent`.

File: dev/generate_protos.py (hunk 11 above)
Comment (harupy) [reply dev/generate_protos.py:35]: makes sense, didn't know that

File: .github/workflows/protobuf-cross-test.yml
Comment (harupy) [inline .github/workflows/protobuf-cross-test.yml:1]: /ai hello, fix this github action workflow. Please make the following updates:

- `protobuf_major_version_plus_one` is confusing. Rename it to `protobuf_major_version` and increment the version before `pip install`.

Comment (harupy) [reply .github/workflows/protobuf-cross-test.yml:1]: @WeichenXu123 you can try this

Comment (WeichenXu123) [reply .github/workflows/protobuf-cross-test.yml:1]: This change failed with error: https://github.com/mlflow/mlflow/actions/runs/9606163544

Comment (harupy) [reply .github/workflows/protobuf-cross-test.yml:1]: That's because you used `${{ protobuf_incremented_version }}`, not `${protobuf_incremented_version}` or `$protobuf_incremented_version`.

File: dev/generate_protos.py [hunk 18]
```diff
@@ -0,0 +1,200 @@
...
+{textwrap.indent(gencode5260, "  ")}
+else:
+{textwrap.indent(gencode3194, "  ")}
+"""
+    out_path.write_text(merged_code, encoding="UTF-8")
+
+
+def main():
+    os.makedirs(cache_dir, exist_ok=True)
+    # with tempfile.TemporaryDirectory() as temp_gencode_dir:
```
Comment (harupy) [inline dev/generate_protos.py:158]:
```suggestion
```

File: dev/generate_protos.py
Comment (harupy) [inline dev/generate_protos.py:1]: /ai any obvious mistakes?

File: .github/workflows/protobuf-cross-test.yml [hunk 19]
```diff
@@ -0,0 +1,81 @@
...
+          pip install .[extras]
+          pip install pyspark
+          # Install Hugging Face datasets to test Hugging Face usage with MLflow dataset tracking
+          pip install datasets
+          # Install TensorFlow to test TensorFlow dataset usage with MLflow dataset tracking
+          pip install tensorflow
+          # Install torch and transformers to test metrics
+          pip install torch transformers
+          pip install -r requirements/test-requirements.txt
+          # Test against specific protobuf versoin
```
Comment (harupy) [inline .github/workflows/protobuf-cross-test.yml:73]: I'd say `Test the latest minor version in protobuf_major_version`.

**Comment by harupy** [comment]
@BenWilson2 could you also take another look?

File: .github/workflows/protobuf-cross-test.yml
Comment (WeichenXu123) [reply .github/workflows/protobuf-cross-test.yml:1]: oh got it!

**Review by harupy — APPROVED** [review]
LGTM

**Review by BenWilson2 — APPROVED** [review]
LGTM once https://github.com/mlflow/mlflow/pull/12360/files#r1647840531 is addressed! Thanks for the clever implementation here @WeichenXu123 :D

File: .github/workflows/protobuf-cross-test.yml [hunk 20]
```diff
@@ -0,0 +1,81 @@
...
+          pip install -r requirements/test-requirements.txt
+          # Test the latest minor version in protobuf_major_version
+          protobuf_incremented_version=$((${{ matrix.protobuf_major_version }} + 1))
+          pip install "protobuf<${ protobuf_incremented_version }"
+      - uses: ./.github/actions/pipdeptree
+      - name: Run tests
+        run: |
+          pytest --splits=${{ matrix.splits }} --group=${{ matrix.group }} \
+            --ignore-flavors --ignore=tests/projects --ignore=tests/examples --ignore=tests/recipes --ignore=tests/evaluate --ignore tests/deployments/server \
+            tests
```
Comment (harupy) [inline .github/workflows/protobuf-cross-test.yml:81]: This can be a follow-up. does this run tests unrelated to protobuf?

Comment (WeichenXu123) [reply .github/workflows/protobuf-cross-test.yml:81]: yes. We can filter out tests unrelated to protobuf, but no simple rules currently

File: .github/workflows/protobuf-cross-test.yml
Comment (harupy) [reply .github/workflows/protobuf-cross-test.yml:1]: @WeichenXu123 

```
% FOO=foo
                                                                                                 
@ mlflow [master] -- INSERT --
% echo "${ FOO }"
zsh: bad substitution
                                                                                                 
@ mlflow [master] -- INSERT --
% echo "${FOO}"
foo
```

Comment (WeichenXu123) [reply .github/workflows/protobuf-cross-test.yml:1]: this works `protobuf<$protobuf_incremented_version`

**Comment by WeichenXu123** [comment]
oh, I found an issue:

```
+ pip install 'protobuf<6'
Requirement already satisfied: protobuf<6 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (4.25.3)
```
I will file a follow-up PR.

**Comment by villainb-dg** [comment]
Any idea when this PR will be released? The upgrade of `protobuf` requirements to 6+ is blocking us from upgrade `grpcio` past `1.63.0`. Thanks

**Comment by BenWilson2** [comment]
@villainb-dg late next week :)

**Comment by villainb-dg** [comment]
@BenWilson2 So it seems that the latest release 4.12.3 did not include your change (https://github.com/mlflow/mlflow/blob/v2.14.3/pyproject.toml#L45). Any idea why?
