### PR TITLE
Un-quarantine four mislabeled xdist-serial test modules

### PR DESCRIPTION
**Pull request by joshuawong-db**
### Stack

> ⚠️ **Stacked on #24459** (pytest-xdist two-pass). This branch is based on `ci-perf-experiment`, so the diff against `master` is cumulative — the xdist infra comes from #24459. Review/merge #24459 first; the net change here is only 10 lines removed from `_XDIST_SERIAL_PATHS` + comment.
>
> Sibling PRs on the same base:
> - #24459 — base: pytest-xdist two-pass
> - #24532 — Spark/Delta Derby isolation
> - #24533 — async export queue spawn-context fix
> - **this PR** — remove 4 mislabeled serial modules

### What

Four modules sat on the serial list with rationales that assumed **cross-worker state leaks**. But pytest-xdist workers are separate OS processes, so `os.environ`, module-level mocks, and imported globals cannot leak between them. The stated races are not possible as described.

- `tests/gateway/providers/test_databricks.py` — all `databricks.sdk` mocks are function-scoped `mock.patch` context managers, restored on exit; the import is lazy. No cross-process leak.
- `tests/db/test_schema.py`, `tests/db/test_tracking_operations.py` — use a per-test `tmp_path` sqlite store (`tests/db/conftest.py`), never `./mlruns`. The only `MLFLOW_ALLOW_FILE_STORE` setter (`tests/store/fs2db`) uses `monkeypatch` (process-local, auto-reverting) and is not even on this list.
- `tests/tracking/_model_registry/test_utils.py` — pure `mock.patch` / `monkeypatch`, no shared filesystem.

### How

Drop all four from `_XDIST_SERIAL_PATHS` and correct the rationale comment.

### Testing

Verified locally: all four modules pass under 2 parallel xdist workers (`pytest ... -n 2 --dist loadscope`) — 66 tests green.

This pull request and its description were written by Isaac.

### CODE REVIEW

**Comment by joshuawong-db** [comment]
Closing this one. CI on the parallel pass falsified the premise.

The analysis assumed these four modules were safe because pytest-xdist workers are separate processes, so `os.environ` / mock / module-global state can't leak **between concurrent workers**. That part is true — but it missed the real mechanism: each worker runs *hundreds* of bulk test modules **sequentially in a single process**, and their global-state leaks contaminate these tests. CI confirmed exactly the originally-documented symptoms:

- `tests/gateway/providers/test_databricks.py::test_sdk_default_credentials` — `AttributeError: module 'databricks' has no attribute 'sdk'`
- `tests/tracking/_model_registry/test_utils.py::test_get_store_sqlalchemy_store[mysql]` — `assert 'sqlite:///tmp/mlruns.db' == 'mysql://hostname/database'` (a sibling module's tracking-store URI bled in via the process-global cache)
- `tests/db/test_tracking_operations.py::test_search_runs` — file-store maintenance-mode error (`MLFLOW_ALLOW_FILE_STORE`) set by a sibling module

These pass in isolation (and under 2 parallel workers locally) but fail inside the full bulk pass. Making them parallel-safe would require per-test resets of process-global singletons (tracking-store registry, the `databricks.sdk` import, the file-store env gate) — fragile plumbing that risks masking real singleton bugs, for essentially zero wall-clock payoff (these are all fast unit tests; the serial tail is dominated by the Spark/subprocess files). Not worth it. They stay quarantined.

The other two serial-tail PRs (#24532 Spark/Delta, #24533 async export queue) attack the heavy files and remain open.
