### ISSUE TITLE
pytest fails with MLflow 3.1.1 but works with 3.0.1 (no other env changes)

### ISSUE THREAD

**Issue by salmankadaya** [mlflow/mlflow#16548]
Description:
When running pytest with MLflow version 3.1.1, I am encountering an error. The same test suite works fine with MLflow version 3.0.1. There are no changes in my test code or other package versions.

This issue started occurring immediately after upgrading MLflow from 3.0.1 to 3.1.1.

Environment:

OS: Ubuntu 22.04

Python version: 3.10.13

PySpark: 3.5.0

delta-spark: 3.0.0

pytest: 7.4.2

pytest-cov: 4.1.0

pytest-sugar: 0.9.7

pytest-mock: 3.11.1

MLflow: 3.0.1 (working) → 3.1.1 (failing)

Steps to Reproduce:

Install MLflow 3.1.1 in a clean environment with the above dependencies.

Run pytest on a suite that runs successfully with MLflow 3.0.1.

Observe the error.

Expected Behavior:
Tests should pass successfully, as they do with MLflow 3.0.1.

Actual Behavior / Error Traceback:

$ poetry.exe run pytest tests/unit/data_engineering/test_abc.py --cov
C:\Users\salmankadaya\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ImportError: cannot import name 'AnalyzeArgument' from 'pyspark.sql.udtf' (C:\Users\salmankadaya\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\udtf.py) (from C:\Users\salmankadaya\Documents\abc\tests\unit\conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest 'C:\Users\salmankadaya\Documents\abc\tests\unit\conftest.py'.
tests\unit\conftest.py:11: in <module>
    from delta import configure_spark_with_delta_pip
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\delta\__init__.py:17: in <module>
    from delta.tables import DeltaTable
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\delta\tables.py:21: in <module>
    import delta.exceptions  # noqa: F401; pylint: disable=unused-variable
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\delta\exceptions\__init__.py:17: in <module>
    from delta.exceptions.base import (
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\delta\exceptions\base.py:17: in <module>
    from pyspark.errors.exceptions.base import PySparkException
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\__init__.py:148: in <module>
    from pyspark.sql import SQLContext, HiveContext, Row  # noqa: F401
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\__init__.py:43: in <module>
    from pyspark.sql.context import SQLContext, HiveContext, UDFRegistration, UDTFRegistration
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\context.py:39: in <module>
    from pyspark.sql.session import _monkey_patch_RDD, SparkSession
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\session.py:48: in <module>
    from pyspark.sql.functions import lit
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\functions\__init__.py:20: in <module>
    from pyspark.sql.functions.builtin import *  # noqa: F401,F403
..\..\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\functions\builtin.py:50: in <module>
    from pyspark.sql.udtf import AnalyzeArgument, AnalyzeResult  # noqa: F401
E   ImportError: cannot import name 'AnalyzeArgument' from 'pyspark.sql.udtf' (C:\Users\salmankadaya\AppData\Local\pypoetry\Cache\virtualenvs\abc-XShEF3g0-py3.10\lib\site-packages\pyspark\sql\udtf.py)

Additional Notes:

I have verified that downgrading MLflow back to 3.0.1 resolves the issue.

No other packages were changed in the environment.

Might be related to recent internal changes in MLflow's type system or schema handling.

**Comment by WeichenXu123** [comment]
`from pyspark.sql.udtf import AnalyzeArgument` this only works in apache/spark >= 4.0

please check whether your `pyspark` version changes before v.s. after

**Comment by salmankadaya** [comment]
No, I have checked pyspark is not updating. For your reference I have attached library details of both the mlflow version. 

[3.0.1.txt](https://github.com/user-attachments/files/21035981/3.0.1.txt)
[3.1.1.txt](https://github.com/user-attachments/files/21035982/3.1.1.txt)

**Comment by WeichenXu123** [comment]
You can do a simple test that:
`pip install pyspark==3.5` then run
```
from pyspark.sql.udtf import AnalyzeArgument
```
it will fail with the `ImportError`

So your 3.0.1 tests should install pyspark 4.0 somewhere. You can `import pyspark` and print `pyspark.__version__` inside your tests code to verify it.

**Comment by emnabarred** [comment]
Hello @salmankadaya,
I ran into a similar issue, and I found out that databricks-connect (a transitive dependency) obseletes the version of pyspark installed and puts its own that is packaged in the wheel....
Apparently this is [known behaviour](https://community.databricks.com/t5/data-engineering/installing-databricks-connect-breaks-pyspark-local-cluster-mode/td-p/67994). [Here ](https://www.reddit.com/r/Python/comments/1n1t36y/is_it_normal_for_a_package_to_overwriteadd_files/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) is a discussion I had on this topic.

**Comment by salmankadaya** [comment]
Hey @emnabarred,
Yes, that's the reason I have bind **databricks-connect = 14.2.1** version so now its working fine.

**Comment by emnabarred** [comment]
> Hey [@emnabarred](https://github.com/emnabarred), Yes, that's the reason I have bind **databricks-connect = 14.2.1** version so now its working fine.

that version also overwrites pyspark but maybe in a way that doesn't impact you.
