### ISSUE TITLE
[BUG] Loading mlflow model using spark_udf fails on Databricks

### ISSUE THREAD

**Issue by leweex95** [mlflow/mlflow#5985]
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

1.20.2

### System information

- **Python version**: 3.8.2.
- **Databricks ML Runtime version**: 9.1.

### Describe the problem

I'm working on Databricks with ML Runtime 9.1 and Mlflow, to build a simple training & inference pipeline, by logging trained models to Mlflow's Model Registry and retrieving it during inference as a `spark_udf`.

I successfully logged the model and artifacts to the Model Registry. Once there, I manually registered the model on the UI, and set the stage to production. In the inference notebook, I simply use the `load_model()` function to load the model, and then `mlflow.pyfunc.spark_udf` to convert the model to spark user defined function.

At this last line, a surprising error shows that I don't understand:
```
ImportError: cannot import name '_SparkDirectoryDistributor' from 
'mlflow.utils._spark_utils' 
(/databricks/python/lib/python3.8/site-packages/mlflow/utils/_spark_utils.py)
```

**Detailed traceback**:
```
ImportError                               Traceback (most recent call last)
<command-1233344365339> in <module>
     25 model = mlflow.sklearn.load_model(model_path)
     26 
---> 27 predict = mlflow.pyfunc.spark_udf(spark, model_uri=model_path, result_type=ArrayType(StringType()))

/databricks/python/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py in spark_udf(spark, model_uri, result_type)
    795 
    796 def get_model_dependencies(model_uri, format="pip"):  # pylint: disable=redefined-builtin
--> 797     """
    798     :param model_uri: The uri of the model to get dependencies from.
    799     :param format: The format of the returned dependency file. If the ``"pip"`` format is

/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py in import_patch(name, globals, locals, fromlist, level)
    160             # Import the desired module. If you’re seeing this while debugging a failed import,
    161             # look at preceding stack frames for relevant error information.
--> 162             original_result = python_builtin_import(name, globals, locals, fromlist, level)
    163 
    164             is_root_import = thread_local._nest_level == 1

/databricks/python/lib/python3.8/site-packages/mlflow/pyfunc/spark_model_cache.py in <module>
----> 1 from mlflow.utils._spark_utils import _SparkDirectoryDistributor
      2 
      3 
      4 class SparkModelCache:
      5     """Caches models in memory on Spark Executors, to avoid continually reloading from disk.

ImportError: cannot import name '_SparkDirectoryDistributor' from 'mlflow.utils._spark_utils' (/databricks/python/lib/python3.8/site-packages/mlflow/utils/_spark_utils.py)
```

### Code to reproduce issue

**training notebook**:
```
import mlflow
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

MODEL_NAME = "model001"

mlflow.start_run()

digits = load_digits()

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target)

logisticRegr = LogisticRegression()
logisticRegr.fit(x_train, y_train)
score = logisticRegr.score(x_test, y_test)

conda_env = mlflow.pyfunc.get_default_conda_env()
        
class MyModel(mlflow.pyfunc.PythonModel):
    def save_context(self, model, path, conda_env):
        artifacts = {'model': path}
        mlflow.sklearn.save_model(sk_model=model, path=artifacts['model'], conda_env=conda_env)

    def load_context(self, context: mlflow.pyfunc.PythonModelContext):
        model = mlflow.sklearn.load_model(context.artifacts['model'])

    def predict(self, context: mlflow.pyfunc.PythonModelContext, input_data):
        return model.predict(input_data.values)

pymodel = MyModel()
pymodel.save_context(logisticRegr, MODEL_NAME, conda_env)

mlflow.sklearn.log_model(artifact_path=MODEL_NAME, sk_model=pymodel, conda_env = conda_env)

mlflow.end_run()
```

**inference notebook**:
```
import mlflow
from mlflow.store.artifact.models_artifact_repo import ModelsArtifactRepository

MODEL_NAME = "model001"

model_path = f"models:/{MODEL_NAME}/production"
model = mlflow.sklearn.load_model(model_path)
predict = mlflow.pyfunc.spark_udf(spark, model_uri=model_path)
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [X] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment]
Hi @leweex95, are you sure you're using `mlflow == 1.20.2`? Your traceback contains code in `mlflow >= 1.25.0`.

**Comment by harupy** [comment]
Somebody may have run a shell command that looks like this on your cluster:

```
%sh

pip install mlflow==1.26.1
```

**Comment by leweex95** [comment]
Hi @harupy 
Unfortunately, that's not the case. I checked mlflow version inside of the notebook where I was running the above commands, and it matched the version that comes preinstalled on Databricks ML Runtime 9.1, version 1.20.2. 
I did run pip install commands earlier on the cluster though, that updated mlflow to a newer version - but I have terminated and restarted the cluster many times since then, and these installations were not even cluster-level, just notebook-level package installations.

**Comment by harupy** [comment]
@leweex95 What does the following command print out?

```
%sh

cat /databricks/python/lib/python3.8/site-packages/mlflow/pyfunc/spark_model_cache.py
```

**Comment by leweex95** [comment]
@harupy the output is:
```
import os
import shutil
import tempfile
import zipfile

from pyspark.files import SparkFiles


class SparkModelCache(object):
    """Caches models in memory on Spark Executors, to avoid continually reloading from disk.

    This class has to be part of a different module than the one that _uses_ it. This is
    because Spark will pickle classes that are defined in the local scope, but relies on
    Python's module loading behavior for classes in different modules. In this case, we
    are relying on the fact that Python will load a module at-most-once, and can therefore
    store per-process state in a static map.
    """

    # Map from unique name --> loaded model.
    _models = {}

    # Number of cache hits we've had, for testing purposes.
    _cache_hits = 0

    def __init__(self):
        pass

    @staticmethod
    def add_local_model(spark, model_path):
        """Given a SparkSession and a model_path which refers to a pyfunc directory locally,
        we will zip the directory up, enable it to be distributed to executors, and return
        the "archive_path", which should be used as the path in get_or_load().
        """
        _, archive_basepath = tempfile.mkstemp()
        # NB: We must archive the directory as Spark.addFile does not support non-DFS
        # directories when recursive=True.
        archive_path = shutil.make_archive(archive_basepath, "zip", model_path)
        spark.sparkContext.addFile(archive_path)
        return archive_path

    @staticmethod
    def get_or_load(archive_path):
        """Given a path returned by add_local_model(), this method will return the loaded model.
        If this Python process ever loaded the model before, we will reuse that copy.
        """
        if archive_path in SparkModelCache._models:
            SparkModelCache._cache_hits += 1
            return SparkModelCache._models[archive_path]

        # BUG: Despite the documentation of SparkContext.addFile() and SparkFiles.get() in Scala
        # and Python, it turns out that we actually need to use the basename as the input to
        # SparkFiles.get(), as opposed to the (absolute) path.
        archive_path_basename = os.path.basename(archive_path)
        local_path = SparkFiles.get(archive_path_basename)
        temp_dir = tempfile.mkdtemp()
        zip_ref = zipfile.ZipFile(local_path, "r")
        zip_ref.extractall(temp_dir)
        zip_ref.close()

        # We must rely on a supposed cyclic import here because we want this behavior
        # on the Spark Executors (i.e., don't try to pickle the load_model function).
        from mlflow.pyfunc import load_pyfunc  # pylint: disable=cyclic-import

        SparkModelCache._models[archive_path] = load_pyfunc(temp_dir)
        return SparkModelCache._models[archive_path]
```

**Comment by harupy** [comment]
Is the inference notebook still failing?

**Comment by leweex95** [comment]
Very interesting - it does run successfully at this time. I'll need to perform further investigations on what might have gone wrong, as I'm very certain the mlflow version was not upgraded from the default one of 1.20.2 that comes preinstalled with Databricks runtime. Strange!

**Comment by harupy** [comment]
@leweex95 Are you using your cluster on your own? or sharing it with somebody in your team?

**Comment by leweex95** [comment]
@harupy just myself, it's a personal cluster only I have access to

**Comment by harupy** [comment]
Strange, please let us know if you find a way that can constantly reproduces the issue.
