### PR TITLE
Probe dropping the `pyspark<4.1.0` pin

### PR DESCRIPTION
**Pull request by harupy**
### Related Issues/PRs

Relates to #25085

### What changes are proposed in this pull request?

Experiment, not a merge candidate as-is: remove `pyspark<4.1.0` from all four places it appears and see what actually breaks.

The stated reason exists only in `pyproject.toml` ("pyspark 4.1.0 causes issues with documentation build"); `test-requirements.txt` and `extra-ml-requirements.txt` carry a bare, unexplained pin. Two things make it worth re-testing:

- The cap excludes 4.2.0 as well as 4.1.x, and 4.2.0 is the release that stopped importing the private `pandas.core.common._builtin_table`. pandas 3 removed it, which is currently five `pyfunc` failures on the Python 3.11 probe. That collateral has never been discussed anywhere in the repo.
- `ml-package-versions.yml` already declares spark `maximum: "4.2.0"`, and cross-version jobs strip these constraints, so the spark flavor is already exercised against 4.2.0. The pin was not protecting it.

`uv lock --upgrade-package pyspark` moves the lock from 4.0.4 to 4.2.0.

Provenance: the pin came from 454df873 in #19409, a DeepEval scorer documentation PR, two days after pyspark 4.1.0 was released. That commit changed a bare `pyspark` to `pyspark<4.1.0` in all four files at once and recorded the reason in `pyproject.toml` only; nothing in the PR discusses it. So this change is a revert to the pre-#19409 state rather than a new relaxation.

What this run should tell us:

- whether the doc build still fails, which would scope the pin to `doc-requirements.txt` alone
- whether any test job actually needed it

It cannot show the `_builtin_table` fix directly, since that needs pandas 3 and master is still on Python 3.10. Rebasing the probe onto this will.

### How is this PR tested?

- [x] Existing unit/integration tests

### Does this PR require documentation update?

- [x] No.

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.

#### Is this a user-facing change?

- [x] No.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/build`: Build and test infrastructure for MLflow

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

- [ ] This PR is critical and needs to be in the next patch release
- [x] This PR can wait for the next minor release

### CODE REVIEW

**Comment by harupy** [comment]
Parked as draft. Blocked upstream, not by anything in this diff.

pyspark 4.2.0 is the only release that works with pandas 3 (4.1.3 still imports the private `pandas.core.common._builtin_table`), but no Delta Lake release is built against Spark 4.2: 4.3.1 targets Spark 4.1 and fails with `NoSuchMethodError` on `CatalogStorageFormat.copy`, and it shipped six days before Spark 4.2.0.

The Python 3.11 upgrade now pins CI to pandas 2 to keep the two efforts independent, so this can wait for a Delta release built against Spark 4.2. The four failure clusters found here are documented above and still apply whenever it is picked back up.
