### PR TITLE
Fix env-var leak flakiness in `test_serving_artifacts_auto_scopes_workspace_paths`

### PR DESCRIPTION
**Pull request by joshuawong-db**
### Related Issues/PRs

Relates to #23401 (surfaced this flaky failure in an unrelated shard)

### What changes are proposed in this pull request?

`test_serving_artifacts_auto_scopes_workspace_paths` installs a fake workspace provider that only implements `resolve_artifact_root`, not `resolve_trace_archival_config`. `create_experiment` only calls `resolve_trace_archival_config` when `MLFLOW_TRACE_ARCHIVAL_CONFIG` is set, so the test passes in isolation.

Under CI sharding (`pytest-split`), a sibling test in the same shard can leave `MLFLOW_TRACE_ARCHIVAL_CONFIG` set in the process environment, causing `create_experiment` to invoke the missing method and fail with:

```
AttributeError: 'TrackingProvider' object has no attribute 'resolve_trace_archival_config'
```

This adds `monkeypatch.delenv(MLFLOW_TRACE_ARCHIVAL_CONFIG.name, raising=False)` at the start of the test, matching the defensive pattern already used by the sibling tests in the same file.

### How is this PR tested?

- [x] Existing unit/integration tests

Reproduced the CI failure locally by exporting `MLFLOW_TRACE_ARCHIVAL_CONFIG` before running the test (fails with the exact `AttributeError`), then confirmed the test passes with the same env var set after the fix.

### Does this PR require documentation update?

- [x] No.

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.

#### Is this a user-facing change?

- [x] No.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/build`: Build and test infrastructure for MLflow

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

- [ ] This PR is critical and needs to be in the next patch release
- [x] This PR can wait for the next minor release

### CODE REVIEW

**Comment by joshuawong-db** [comment]
/review-v2

---

🚀 [NaiLaOpus running...](https://github.com/mlflow/mlflow/actions/runs/31658823839?pr=25055)

File: tests/store/tracking/sqlalchemy_store/test_sqlalchemy_workspace_store.py [hunk 1]
```diff
@@ -371,6 +371,7 @@ def test_artifact_locations_are_scoped_to_workspace(workspace_tracking_store):
 
 
 def test_serving_artifacts_auto_scopes_workspace_paths(workspace_tracking_store, monkeypatch):
+    monkeypatch.delenv(MLFLOW_TRACE_ARCHIVAL_CONFIG.name, raising=False)
```
[the remark this answers is not in the document]
Comment (joshuawong-db) [reply tests/store/tracking/sqlalchemy_store/test_sqlalchemy_workspace_store.py:374]: Good catch — fixed in fe2c667. Added the matching `monkeypatch.delenv(MLFLOW_TRACE_ARCHIVAL_CONFIG.name, raising=False)` so the archival path can't activate against `EmptyProvider`.

**Comment by joshuawong-db** [comment]
/review-v2

---

🚀 [NaiLaOpus running...](https://github.com/mlflow/mlflow/actions/runs/31663388686?pr=25055)
