### PR TITLE
Implement concrete `from_proto` on `UCSchemaLocation` and `UnityCatalog`

### LINKED ISSUE #23505: [NIT] UnityCatalog trace location: @abstractmethod from_proto inherited but unimplemented (mypy false positive on instantiation)
> [!WARNING]
> Before submitting a PR, please make sure that:
> - A maintainer has triaged this issue and applied the `ready` label
> - This issue has no assignee
> - No duplicate PR exists
>
> PRs not meeting these requirements may be automatically closed.

### Issues Policy acknowledgement
- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?
Local machine

### MLflow version
- Client: 3.12.0
- Tracking server: N/A (issue is in the client-side entity class)

### System information
- **OS Platform and Distribution**: macOS 26.4.1 (darwin 25.4.0)
- **Python version**: 3.11 and 3.12 (both reproduce)

### Describe the problem

`mlflow.entities.trace_location.UnityCatalog` cannot be instantiated according
to mypy: it inherits an unimplemented `@abstractmethod from_proto` from
`_MlflowObject` (via `TraceLocationBase`). At runtime the `@experimental` +
`@dataclass` decorators on `UnityCatalog` rebuild the class and drop
`__abstractmethods__`, so `UnityCatalog(...)` succeeds. mypy reads the source
faithfully and (correctly) rejects every call site with:

```
error: Cannot instantiate abstract class "UnityCatalog" with abstract attribute "from_proto"  [abstract]
```

**Expected:** `UnityCatalog(...)` type-checks cleanly, matching its runtime
behavior and the example in the `set_experiment` docs.

**Actual:** Every caller must add `# type: ignore[abstract]`, even though
the class is part of the public `mlflow.entities.trace_location` surface and
is the documented way to set a UC trace location.

`UnityCatalog` was introduced in PR #21184 and marked `@experimental` in
commit 47dc6a9; neither change provided a concrete `from_proto`.

### Tracking information

N/A — this is a static-typing issue at the entity-class level, not a tracking-server interaction.

### Code to reproduce issue

```python
# pip install "mlflow==3.12.0" mypy
# file: repro.py
from mlflow.entities.trace_location import UnityCatalog

uc = UnityCatalog(catalog_name="c", schema_name="s")
print(UnityCatalog.__abstractmethods__)  # -> frozenset()  (runtime is happy)
```

```
$ python repro.py
frozenset()

$ mypy repro.py
repro.py:3: error: Cannot instantiate abstract class "UnityCatalog" with abstract attribute "from_proto"  [abstract]
Found 1 error in 1 file (checked 1 source file)
```

### Stack trace

N/A — this is a mypy diagnostic, not a runtime exception. The full mypy output is included in the repro section above.

### Other info / logs

**Root cause.** `_MlflowObject.from_proto` is declared:

```python
@classmethod
@abstractmethod
def from_proto(cls, proto):
    pass
```

`UnityCatalog` inherits this through `TraceLocationBase` and never overrides
it. `@dataclass` (and `@experimental`, which rebuilds the class) strip
`__abstractmethods__` at runtime, masking the unmet contract from
`abc.ABCMeta`. mypy sees the source contract and refuses the instantiation.

**Proposed fixes (either resolves the false positive).**

1. **Drop `@abstractmethod` on `_MlflowObject.from_proto`** (keep the
   `@classmethod`). The contract is already enforced informally by callers
   that invoke `from_proto`; no concrete subclass appears to rely on `ABC`
   to block accidental instantiation.

2. **Explicitly implement `from_proto` on `UnityCatalog`** (and any other
   concrete `TraceLocationBase` subclass that currently inherits the
   abstract stub). Lower-risk; keeps the abstract contract intact for
   genuinely-incomplete subclasses.

### What component(s) does this bug affect?
- [x] `area/tracing`

### PR DESCRIPTION
**Pull request by kishor-rkrishnan**
### Related Issues/PRs

Closes #23505

### What changes are proposed in this pull request?

`UnityCatalog` and `UCSchemaLocation` inherit an `@abstractmethod from_proto` from `_MlflowObject` (via `TraceLocationBase`) but never override it. At runtime the `@dataclass` / `@experimental` decorators rebuild the class and drop `__abstractmethods__`, so instantiation succeeds — but mypy reads the source contract faithfully and rejects every call site with:

```
error: Cannot instantiate abstract class "UnityCatalog" with abstract attribute "from_proto"  [abstract]
```

This forces every caller to add `# type: ignore[abstract]`, even though these classes are part of the public `mlflow.entities.trace_location` surface and are the documented way to set a UC trace location.

This PR follows **option 2** from the issue: it adds concrete `from_proto` classmethods to both `UCSchemaLocation` and `UnityCatalog`, each delegating to the existing `uc_schema_location_from_proto` / `uc_table_prefix_location_from_proto` helpers in `mlflow.utils.databricks_tracing_utils`. This resolves the mypy false positive without duplicating logic and keeps the abstract contract intact for genuinely-incomplete subclasses (lower risk than dropping `@abstractmethod` on the base).

### How is this PR tested?

- [x] Existing unit/integration tests
- [x] New unit/integration tests
- [ ] Manual tests

Added `tests/entities/test_trace_location.py` cases covering the `from_proto` round-trips for both classes plus a regression guard asserting neither class is mistakenly abstract again (`__abstractmethods__ == frozenset()`).

### Does this PR require documentation update?

- [x] No.

### Does this PR require updating the [MLflow Skills](https://github.com/mlflow/skills) repository?

- [x] No.

#### Is this a user-facing change?

- [x] No.

#### What component(s), interfaces, languages, and integrations does this PR affect?

Components

- [x] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality

<a name="release-note-category"></a>

#### How should the PR be classified in the release notes? Choose one:

- [x] `rn/none` - No description will be included. The PR will be mentioned only by the PR number in the "Small Bugfixes and Documentation Updates" section

#### Is this PR a critical bugfix or security fix that should go into the next patch release?

- [ ] This PR is critical and needs to be in the next patch release
- [x] This PR can wait for the next minor release

### CODE REVIEW

**Comment by kishor-rkrishnan** [comment]
@WeichenXu123  Can you assign the related issue to me and help to reopen this PR

File: tests/entities/test_trace_location.py [hunk 1]
```diff
@@ -162,3 +163,43 @@ def test_unity_catalog_inequality_on_different_prefix():
...
+    assert location._otel_logs_table_name == "logs"
+    assert location._annotations_table_name == "anns"
+
+
+def test_uc_classes_are_concretely_instantiable():
+    # Regression: ensure neither class is mistakenly abstract again.
+    # mypy `Cannot instantiate abstract class` would re-appear if `from_proto`
+    # is dropped on either class without overriding the abstract method elsewhere.
+    assert UCSchemaLocation.__abstractmethods__ == frozenset()
+    assert UnityCatalog.__abstractmethods__ == frozenset()
```
Comment (kriscon-db) [inline tests/entities/test_trace_location.py]: This regression guard doesn't actually guard the fix — it passes whether or not the `from_proto` overrides exist. `from_proto` is declared `@abstractmethod` on `_MlflowObject`, but [`_MlflowObject` is a plain `type`, not an `ABCMeta` class](https://github.com/mlflow/mlflow/blob/17661c6adcd52d1bfe8174c5c1044486a6e56755/mlflow/entities/_mlflow_object.py#L6), so the abstractmethod is never enforced and `__abstractmethods__` is already `frozenset()` on both classes on `master` (before this PR). I checked out the pre-PR tree and confirmed both asserts pass with the two new `from_proto` methods deleted.

The mypy `[abstract]` error this PR fixes is a *static* check; `__abstractmethods__` is a *runtime* attribute, so the two are unrelated — the comment on lines 201–203 ties them together but the assert can't observe the mypy regression it describes. Worth noting this repo's mypy hook is also scoped to `dev/` and `.claude/skills/` ([`.pre-commit-config.yaml`](https://github.com/mlflow/mlflow/blob/17661c6adcd52d1bfe8174c5c1044486a6e56755/.pre-commit-config.yaml#L57-L76)), so `mlflow/entities/` isn't type-checked in CI either way.

Would a `dict`-level guard be closer to what you want — e.g. `assert "from_proto" in UCSchemaLocation.__dict__` (and the same for `UnityCatalog`), which does fail if either override is dropped? Or drop the test, since the two `from_proto` tests above already exercise the methods directly?

-- Claude-drafted, reviewed before posting.

Comment (kishor-rkrishnan) [reply tests/entities/test_trace_location.py]: You're right on all counts — thanks for digging into this. I confirmed it locally: _MlflowObject is a plain type with no __abstractmethods__, so ABCMeta never picks up its @abstractmethod from_proto — TraceLocationBase.__abstractmethods__ is just {'to_dict', 'from_dict'}. A subclass that overrides only those two instantiates fine with from_proto deleted, so the assert passes either way and never observes the (static) mypy error it claims to guard.

 I've dropped test_uc_classes_are_concretely_instantiable along with the misleading comment. The two from_proto round-trip tests right above it are the real regression guard: if either override is removed, the class falls back to the pass-body abstract stub, from_proto() returns None, and those tests fail on the attribute access. So coverage for the actual fix is already in place without the no-op assert.

**Review by kriscon-db — APPROVED** [review]
LGTM
