### ISSUE TITLE
[BUG] missing 1 required positional argument: 'start_response'

### ISSUE THREAD

**Issue by carno** [mlflow/mlflow#17324]
### Issues Policy acknowledgement

- [x] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### MLflow version

```
mlflow --version
mlflow, version 3.3.1
```

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker
- **Python version**: 3.10.18
- **yarn version, if running the dev UI**: N/A

### Describe the problem

Since version 3.3.0, when using authentication (mlflow[auth]) trying to access main page or `/health` endpoint gives 500 Internal error

### Tracking information

```shell
N/A
```

### Code to reproduce issue

```
docker run -it --rm -p 5000:5000 ghcr.io/mlflow/mlflow:v3.3.0 bash

/# export MLFLOW_FLASK_SERVER_SECRET_KEY=qwertyuiop
/# python -m pip install --update mlflow[auth]
mlflow server --host 0.0.0.0 --port 5000 --app-name=basic-auth
```

and access `http://localhost:5000/` in the browser (or `http://localhost:5000/health`)

### Stack trace

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/asgi2.py", line 14, in __call__
    instance = self.app(scope)
TypeError: Flask.__call__() missing 1 required positional argument: 'start_response'
```

### Other info / logs

```
N/A
```

### What component(s) does this bug affect?

- [x] `area/tracking`: Tracking Service, tracking client APIs, autologging
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/scoring`: MLflow model serving, deployment tools, Spark UDFs
- [ ] `area/evaluation`: MLflow model evaluation features, evaluation metrics, and evaluation workflows
- [ ] `area/prompt`: MLflow prompt engineering features, prompt templates, and prompt management
- [ ] `area/tracing`: MLflow Tracing features, tracing APIs, and LLM tracing functionality
- [ ] `area/gateway`: MLflow AI Gateway client APIs, server, and third-party integrations
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/uiux`: Front-end, user experience, plotting
- [ ] `area/docs`: MLflow documentation pages

**Comment by freymend** [comment]
Also running into this issue

### MLflow version

```
mlflow --version
mlflow, version 3.3.1
```

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Docker
- **Python version**: 3.13
- **yarn version, if running the dev UI**: N/A

**Comment by anandakumar-ds** [comment]
Facing the same issue after upgrading to 3.3.1 from 3.2.0

**Comment by anandakumar-ds** [comment]
Temporarily got out of the error by explicitly running the server on gunicorn instead of uvicorn (added `--gunicorn-opts "--timeout=120"` when starting server)

**Comment by hermda02** [comment]
Also running into this error after upgrading from 3.1.1.

Everything runs fine without the `--app-name=basic-auth` flag.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Docker
- **Python version:** 3.10
- **yarn version, if running the dev UI:** N/A

**Comment by retzero** [comment]
> Temporarily got out of the error by explicitly running the server on gunicorn instead of uvicorn (added `--gunicorn-opts "--timeout=120"` when starting server)

It works but I got this warning message with this option;

```
/usr/local/lib/python3.10/site-packages/mlflow/cli.py:453: 
  FutureWarning: We recommend using uvicorn for improved performance. 
  Please use uvicorn by default or specify '--uvicorn-opts' instead of '--gunicorn-opts'.
```

**Comment by daniellok-db** [comment]
Thanks for the report, we'll investigate!

**Comment by moulin-louis** [comment]
+1 here when upgrading from MLFlow 3.2.0 to 3.3.1 with basic-auth enabled.

**Comment by daniellok-db** [comment]
Looks like we missed updating the auth app to work with uvicorn when we made it the default. Sorry for the inconvenience, we'll try to get this fixed soon, but in the meantime please continue using the gunicorn app by specifying `--gunicorn-ops '<options, can be empty>'` as mentioned above
